osx_image: xcode8.2
language: objective-c
cache:
  - pip
  - cocoapods
install:
  - gem install fastlane --no-ri --no-doc --no-document
  - pod install
script:
  - fastlane snapshot --verbose --derived_data_path derivedData --skip_open_summary
after_success:
  - bash <(curl -s https://api.sightr.io/bash) -t 596e7f656abe96000f798955 -d screenshots
