osx_image: xcode8.2
language: objective-c
cache:
  - pip
  - cocoapods
install:
  - pip install awscli
  - gem install fastlane --no-ri --no-doc --no-document
  - pod install
script:
  - fastlane snapshot --verbose --derived_data_path derivedData --skip_open_summary
after_success:
  - curl "https://api.sightr.io/uploadscript?repoKey=596e7f656abe96000f798955&branch=$TRAVIS_BRANCH&ci=travis&build=$TRAVIS_BUILD_NUMBER&directory=screenshots&commit=$TRAVIS_COMMIT" | bash
  
