osx_image: xcode8.2
language: objective-c
cache:
  - pip
  - cocoapods
install:
  - pip install awscli
  - gem install fastlane --no-ri --no-doc --no-document
  - pod install
script:
  - fastlane snapshot --verbose --derived_data_path derivedData --skip_open_summary
  - xctool -project "Movies.xcworkspace" -scheme "Movies" build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - curl "https://api.sightr.io/uploadscript?repoKey=596e7f656abe96000f798955&branch=$TRAVIS_BRANCH&ci=travis&build=$TRAVIS_BUILD_NUMBER&directory=screenshots&commit=$TRAVIS_COMMIT" | bash
  - bash <(curl -s https://codecov.io/bash) -t ef7c8198-7246-4360-9b3a-1cfd8f2a5ff5
  
