osx_image: xcode8.2
language: objective-c
cache:
  - cocoapods
install:
  - gem install fastlane --no-ri --no-doc --no-document
  - pod install
script:
  - fastlane snapshot --derived_data_path derivedData --skip_open_summary
after_success:
  - bash <(curl -s -L https://serverless.sightr.io/v1/bash) -t 5a06ef9587742f0001d3dffe -d screenshots
